apiVersion: v1
kind: Namespace
metadata:
  name: team1
  labels:
    name: team1
    app.kubernetes.io/part-of: kagenti
    istio-injection: enabled
    kagenti-enabled: "true"  # Allows kagenti UI to discover this namespace
