apiVersion: v1
kind: ConfigMap
metadata:
  name: global-environments
  namespace: kagenti-system
  labels:
    app: kagenti-ui
data:
  KEYCLOAK_URL: "http://keycloak.keycloak.svc.cluster.local:8080"
  KEYCLOAK_PUBLIC_URL: "https://keycloak.localtest.me:9443"
  KEYCLOAK_REALM: "master"
  KEYCLOAK_ADMIN_USERNAME: "admin"
  KEYCLOAK_ADMIN_PASSWORD: "admin123"
