apiVersion: v1
kind: Namespace
metadata:
  name: kiali
  labels:
    app.kubernetes.io/name: kiali
    app.kubernetes.io/part-of: kagenti
    app.kubernetes.io/component: observability
    istio-injection: enabled
