apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gateway-api
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "0"
  labels:
    kagenti.dev/layer: infrastructure
    kagenti.dev/component: gateway-api
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Ladas/kagenti-demo-deployment.git
    targetRevision: argocd-gitops-dev-phase-1
    path: components/00-infrastructure/gateway-api
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
