---
apiVersion: v1
kind: Service
metadata:
  name: phoenix
  namespace: observability
  labels:
    app: phoenix
    app.kubernetes.io/name: phoenix
    app.kubernetes.io/part-of: kagenti
    app.kubernetes.io/component: observability
spec:
  type: ClusterIP
  ports:
    - port: 6006
      targetPort: 6006
      protocol: TCP
      name: http
  selector:
    app: phoenix
