apiVersion: v1
kind: Service
metadata:
  name: mcp-inspector
  namespace: kagenti-system
  labels:
    app: mcp-inspector
    app.kubernetes.io/name: mcp-inspector
spec:
  selector:
    app: mcp-inspector
  ports:
  - name: ui
    port: 6274
    protocol: TCP
    targetPort: 6274
  - name: proxy
    port: 6277
    protocol: TCP
    targetPort: 6277
  type: ClusterIP
